export const data = [
  {
    category: "shishas",
    image: "/images/shisha-01.jpg",
    subcategories: [
      {
        slug: "7-days",
        name: "7 Days",
        image: "/images/shisha-03.jpg",
        products: [
          {
            id: 1,
            name: "Double Apple",
            desc: "Social smoke shisha",
            price: 20,
            reagent: "123",
          },
        ],
      },
      {
        slug: "grace-shishas",
        name: "Grace Shishas",
        image: "/images/shisha-01.jpg",
        products: [
          {
            id: 2,
            name: "Mint Chocolate",
            desc: "Social smoke shisha",
            price: 25,
            reagent: "123",
          },
          {
            id: 3,
            name: "Tropical Mix",
            desc: "Social smoke shisha",
            price: 30,
            reagent: "123",
          },
        ],
        reagents: {
          1: "Mint",
          2: "Chocolate",
          3: "Tropical",
          4: "Mix",
          5: "Double",
        },
      },
      {
        name: "Social Smoke",
        slug: "social-smoke",
        image: "/images/shisha-02.jpg",
        products: [
          {
            id: 2,
            name: "Mint Chocolate",
            price: 25,
            desc: "Social smoke shisha",
            reagent: "123",
          },
          {
            id: 3,
            name: "Tropical Mix",
            price: 30,
            desc: "Social smoke shisha",
            reagent: "123",
          },
        ],
      },
    ],
  },
  {
    category: "cocktails",
    image: "/images/cocktail-01.jpg",
    subcategories: [
      {
        name: "Grace Coctails",
        slug: "grace-coctails",
        image: "/images/cocktail-01.jpg",
        products: [
          {
            id: 4,
            name: "Mojito",
            price: 200,
            description: "Easy to light",
          },
          {
            id: 5,
            name: "Mojito Strawberry",
            price: 200,
            description: "Long-lasting",
          },
          {
            id: 5,
            name: "Strawberry",
            price: 200,
            description: "Long-lasting",
          },
          {
            id: 5,
            name: "Pure Strawberry",
            price: 200,
            description: "Long-lasting",
          },
          {
            id: 5,
            name: "Cherry",
            price: 200,
            description: "Long-lasting",
          },
          {
            id: 5,
            name: "Pina Colada",
            price: 200,
            description: "Long-lasting",
          },
          {
            id: 5,
            name: "Sex on the beach",
            price: 200,
            description: "Long-lasting",
          },
          {
            id: 5,
            name: "Blue Lagoon",
            price: 200,
            description: "Long-lasting",
          },
          {
            id: 5,
            name: "Passion Fruit",
            price: 200,
            description: "Long-lasting",
          },
          {
            id: 5,
            name: "Green Cat",
            price: 200,
            description: "Long-lasting",
          },
          {
            id: 5,
            name: "Mango",
            price: 200,
            description: "Long-lasting",
          },
          {
            id: 5,
            name: "Grace Cocktail",
            price: 350,
            description: "Long-lasting",
          },
        ],
      },
      {
        name: "Red Bull Cocktails",
        slug: "redbull-coctails",
        image: "/images/cocktail-02.jpg",
        products: [
          {
            id: 4,
            name: "Red Bull Tropical Pleasure",
            price: 270,
            description: "Easy to light",
          },
          {
            id: 5,
            name: "Red Bull Colada",
            price: 270,
            description: "Long-lasting",
          },
          {
            id: 5,
            name: "Red Bull Goes Down",
            price: 270,
            description: "Long-lasting",
          },
          {
            id: 5,
            name: "Red Bull Watermelon Pleasure",
            price: 270,
            description: "Long-lasting",
          },
        ],
      },
    ],
  },
  {
    category: "food",
    image: "/images/food-01.jpg",
    subcategories: [
      {
        name: "Pizza",
        slug: "pizza",
        image: "/images/food-01.jpg",
        products: [
          {
            id: 6,
            name: "Pizza Capricciosa",
            price: 10,
            description: "Keeps your hose fresh",
          },
          {
            id: 7,
            name: "Pizza Tuna",
            price: 15,
            description: "Reduces heat",
          },
          {
            id: 7,
            name: "Pizza Margarita",
            price: 15,
            description: "Reduces heat",
          },
          {
            id: 7,
            name: "Pizza Quattro Formaggi",
            price: 15,
            description: "Reduces heat",
          },
          {
            id: 7,
            name: "Pizza Vegetariana",
            price: 15,
            description: "Reduces heat",
          },
          {
            id: 7,
            name: "Pizza Calzone",
            price: 15,
            description: "Reduces heat",
          },
          {
            id: 7,
            name: "Pizza Solenka",
            price: 15,
            description: "Reduces heat",
          },
          {
            id: 7,
            name: "Mini Pizza",
            price: 15,
            description: "Reduces heat",
          },
          {
            id: 7,
            name: "Pizza Grace",
            price: 15,
            description: "Reduces heat",
          },
          {
            id: 7,
            name: "Club Sandwich",
            price: 15,
            description: "Reduces heat",
          },
          {
            id: 7,
            name: "Pizza Rucola",
            price: 15,
            description: "Reduces heat",
          },
        ],
      },
      {
        name: "Desserts",
        slug: "desserts",
        image: "/images/desert-01.png",
        products: [
          {
            id: 6,
            name: "Crape 1/2 (Pallacink)",
            price: 10,
            description: "Keeps your hose fresh",
          },
          {
            id: 7,
            name: "Crape (Pallacinka)",
            price: 15,
            description: "Reduces heat",
          },
          {
            id: 7,
            name: "Waffle With Fruits",
            price: 15,
            description: "Reduces heat",
          },
          {
            id: 7,
            name: "Crape With Nutella",
            price: 15,
            description: "Reduces heat",
          },
          {
            id: 7,
            name: "Chocolate Lava (Ftoht - Ngroht)",
            price: 15,
            description: "Reduces heat",
          },
        ],
      },
      {
        name: "Snacks",
        slug: "snacks",
        image: "/images/food-01.jpg",
        products: [
          {
            id: 6,
            name: "Nachos With Sauce",
            price: 10,
            description: "Keeps your hose fresh",
          },
          {
            id: 7,
            name: "Nachos",
            price: 15,
            description: "Reduces heat",
          },
        ],
      },
    ],
  },
  {
    category: "drinks",
    image: "/images/desert-01.png",
    subcategories: [
      {
        name: "Cold Drinks",
        slug: "cold-drinks",
        image: "/images/drink-01.png",
        products: [
          {
            id: 5,
            name: "Coca Cola",
            price: "90 Den",
            description: " ",
          },
          {
            id: 5,
            name: "Coca Cola Zero",
            price: "90 Den",
            description: " ",
          },
          {
            id: 5,
            name: "Fanta Orange",
            price: "90 Den",
            description: " ",
          },
          {
            id: 5,
            name: "Fanta Shokata",
            price: "90 Den",
            description: " ",
          },
          {
            id: 5,
            name: "Schweppes",
            price: "90 Den",
            description: " ",
          },
          {
            id: 5,
            name: "Schweppes Tonic",
            price: "90 Den",
            description: " ",
          },
          {
            id: 5,
            name: "Schweppes Tangerine",
            price: "90 Den",
            description: " ",
          },
          {
            id: 5,
            name: "Sprite",
            price: "90 Den",
            description: " ",
          },
          {
            id: 5,
            name: "Kiwi Juice",
            price: "80 Den",
            description: " ",
          },
          {
            id: 5,
            name: "Pineapple Juice",
            price: "80 Den",
            description: " ",
          },
          {
            id: 5,
            name: "Still Water",
            price: "70 Den",
            description: " ",
          },
          {
            id: 5,
            name: "Mineral Water",
            price: "70 Den",
            description: " ",
          },
        ],
      },
      {
        name: "Bravo Drinks",
        slug: "bravo-drinks",
        image: "/images/drink-01.png",
        products: [
          {
            id: 6,
            name: "Bravo Strawberry",
            price: "90 Den",
            description: " ",
          },
          {
            id: 6,
            name: "Bravo Orange",
            price: "90 Den",
            description: " ",
          },
          {
            id: 6,
            name: "Bravo Apple",
            price: "90 Den",
            description: " ",
          },
          {
            id: 6,
            name: "Bravo Peach",
            price: "90 Den",
            description: " ",
          },
          {
            id: 6,
            name: "Bravo Blueberry",
            price: "90 Den",
            description: " ",
          },
          {
            id: 6,
            name: "Bravo Multivitamin",
            price: "90 Den",
            description: " ",
          },
          {
            id: 6,
            name: "Bravo Cherry",
            price: "90 Den",
            description: " ",
          },
          {
            id: 6,
            name: "Bravo Strawberry Banana",
            price: "90 Den",
            description: " ",
          },
          {
            id: 6,
            name: "Bravo Ice Tea Lemon",
            price: "90 Den",
            description: " ",
          },
          {
            id: 6,
            name: "Bravo Ice Tea Peach",
            price: "90 Den",
            description: " ",
          },
        ],
      },
      {
        name: "Red Bull",
        slug: "redbull-drinks",
        image: "/images/drink-01.png",
        products: [
          {
            id: 7,
            name: "Red Bull",
            price: "200 Den",
            description: " ",
          },
          {
            id: 7,
            name: "Red Bull Sugarfree",
            price: "200 Den",
            description: " ",
          },
          {
            id: 7,
            name: "Red Bull The Yellow Edition",
            price: "200 Den",
            description: " ",
          },
          {
            id: 7,
            name: "Red Bull The Red Edition",
            price: "200 Den",
            description: " ",
          },
        ],
      },
      {
        name: "Hot Drinks",
        slug: "hot-drinks",
        image: "/images/drink-01.png",
        products: [
          {
            id: 8,
            name: "Espresso",
            price: "50",
            description: " ",
          },
          {
            id: 8,
            name: "Macchiato",
            price: "50",
            description: " ",
          },
          {
            id: 8,
            name: "Americano",
            price: "50",
            description: " ",
          },
          {
            id: 8,
            name: "Cappuccino",
            price: "50",
            description: " ",
          },
          {
            id: 8,
            name: "Large Macchiato",
            price: "60",
            description: " ",
          },
          {
            id: 8,
            name: "Large Cappuccino",
            price: "60",
            description: " ",
          },
          {
            id: 8,
            name: "Latte Macchiato",
            price: "80",
            description: " ",
          },
          {
            id: 8,
            name: "Nescafe",
            price: "80",
            description: " ",
          },
          {
            id: 8,
            name: "Iced Coffee",
            price: "70",
            description: " ",
          },
          {
            id: 8,
            name: "Hot Chocolate",
            price: "150",
            description: " ",
          },
          {
            id: 8,
            name: "Bambi",
            price: "200",
            description: " ",
          },
          {
            id: 8,
            name: "Tea",
            price: "60",
            description: " ",
          },
        ],
      },
    ],
  },
];
